version: '3.8'

services:
  inventory:
    build: ./inventory-service
    ports:
      - '3003:3003'
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/inventory

  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
